apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: consul-ui
  annotations:
    kubernetes.io/ingress.class: "haproxy"
spec:
  rules:
  - host: consul.kube.noverit.com
    http:
      paths:
      - path: /
        backend:
          serviceName: consul
          servicePort: 8500
      - path: /metrics
        backend:
          serviceName: consul-metrics
          servicePort: 9107

