apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace:
  labels:
    run: nginx
spec:
  containers:
  - name: container
    image: docker.io/bitnami/nginx:1.19-debian-10
    ports:
    - containerPort: 8080
