apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  labels:
  namespace:
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    #nodePort: 80
  selector:
    run: nginx
  type: NodePort
