apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  restartPolicy: Always
  containers:
  - name: container-1
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
