apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: 
  name: nginx
  annotations:
    #kubernetes.io/ingress.class:
spec:
  rules:
  - host: web.demo.noverit.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
