apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wordpress
  annotations:
    kubernetes.io/ingress.class: "haproxy"
spec:
  rules:
  - host: blog.kube.noverit.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress 
          servicePort: 80